import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Baca .env.local
const envPath = path.resolve(__dirname, '.env.local');
const envStr = fs.readFileSync(envPath, 'utf8');

const env = Object.fromEntries(
  envStr.split('\n')
    .filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => l.split('=').map(s => s.trim()))
);

const supabaseUrl = env['NEXT_PUBLIC_SUPABASE_URL'];
const supabaseKey = env['SUPABASE_SERVICE_ROLE_KEY'] || env['NEXT_PUBLIC_SUPABASE_ANON_KEY'];

if (!supabaseUrl || !supabaseKey || supabaseUrl.includes('YOUR_')) {
  console.error('❌ Supabase URL/KEY tidak ditemukan di .env.local');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const scenarios = [
  // ==================== HETERO PRIA (15) ====================
  { id: 'adik_ipar_pria', title: 'Adik Ipar Cewek', description: 'Adik ipar yang selalu pakai daster tipis tanpa bra, memeknya sudah basah tiap kali kamu lewat dapur malam-malam. Tatap matanya penuh nafsu, paha gesek pelan, bisik "Kak... aku kepanasan nih" sambil gigit bibir – sinyal dia lagi sange berat, siap dimancing sampai memeknya banjir sebelum kontolmu masuk.', thumbnail: 'https://placeholder.com/200x300?text=Adik+Ipar+Cewek', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi taboo: Adik Ipar Cewek. Perspektif pria. Mulai dari scene netral di rumah malam hari. Fokus slow-burn build-up minimal 5 scene: membaca sinyal gairah (napas cepat, tatap lama, gigit bibir, paha gesek, pupil melebar, suara serak, dll) dan memancing halus (kata ambigu, sentuhan tidak sengaja, bisik dekat telinga, proximity, teasing ringan). Kalau gagal membaca sinyal -> cerita berakhir awkward tanpa sex. Kalau berhasil -> naik ke foreplay ringan -> edging -> blended orgasm kalau pilihan benar. Bahasa Indonesia vulgar + slang.' },
  { id: 'kakak_ipar_pria', title: 'Kakak Ipar Cewek', description: 'Kakak ipar seksi yang suka "kebetulan" buka kancing atas saat ngobrol, putingnya nongol samar-samar. Napasnya cepat, mata melotot ke kontolmu yang mulai keras di celana – dia lagi memancing supaya kamu berani pegang payudaranya yang montok sebelum ngentot dia di sofa.', thumbnail: 'https://placeholder.com/200x300?text=Kakak+Ipar+Cewek', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi taboo: Kakak Ipar Cewek. Perspektif pria. Latar: acara keluarga atau ngobrol berdua di sofa. Fokus atraksi fisik, memancing respons, dan sentuhan "tidak sengaja", slow-burn 5 scene.' },
  { id: 'ibu_mertua_pria', title: 'Ibu Mertua', description: 'Ibu mertua masih hot, daster ketat bikin kontolmu tegang tiap dia lewat. Napas berat, tatap lama ke selangkanganmu, paha saling gesek – sinyal dia lagi pengen kontol menantunya masuk dalam memeknya yang sudah licin, tapi harus dimancing pelan-pelan dulu.', thumbnail: 'https://placeholder.com/200x300?text=Ibu+Mertua', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi taboo: Ibu Mertua. Perspektif pria. Fokus di usia yang mature tapi nafsu besar. Slow-burn: membaca gestur, memancing lewat pujian dan kedekatan intim secara bertahap.' },
  { id: 'pembantu_art_pria', title: 'Pembantu Rumah (ART)', description: 'Pembantu muda rok pendek tanpa celana dalam, memeknya kelihatan samar saat membungkuk. Napasnya tersengal, mata genit ke kontolmu – dia lagi sange berat, siap dimancing sampai kamu angkat roknya dan masukin kontol ke memek basahnya di dapur.', thumbnail: 'https://placeholder.com/200x300?text=Pembantu+ART', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: ART Cewek. Perspektif pria. Posisi dominan. Mulai dengan instruksi biasa yang berkembang jadi ambigu. Sinyal gairah: membungkuk disengaja, curi pandang. Slow-burn build-up wajib.' },
  { id: 'istri_sahabat_pria', title: 'Istri Sahabat Terbaik', description: 'Istri sahabat yang selalu pakai tanktop ketat, putingnya nongol saat ketawa. Tatap matanya penuh nafsu ke kontolmu, paha gesek pelan – dia lagi memancing supaya kamu berani pegang memeknya yang sudah banjir sebelum ngentot dia di kamar mandi pesta.', thumbnail: 'https://placeholder.com/200x300?text=Istri+Sahabat', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Istri Sahabat. Perspektif Pria. Tantangan psikologis (pengkhianatan). Sinyal: curi pandang di depan suami, obrolan ambigu berdua. Harus slow-burn dan menantang bahaya ketahuan.' },
  { id: 'sepupu_kandung_pria', title: 'Sepupu Kandung Cewek', description: 'Sepupu yang baru pulang kampung, baju ketat bikin kontolmu keras. Napas cepat, gigit bibir saat tatapmu, tangan gemetar – sinyal dia lagi pengen kontol sepupunya masuk memeknya, tapi harus dimancing pelan dulu biar nggak ketahuan keluarga.', thumbnail: 'https://placeholder.com/200x300?text=Sepupu+Cewek', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi taboo: Sepupu Cewek. Nostalgia masa kecil berujung gairah dewasa. Sinyal: jarak fisik yang kelewat batas teman, napas memburu saat dibahas masa lalu. Slow-burn memancing batas kekerabatan.' },
  { id: 'dosen_guru_pria', title: 'Dosen / Guru Privat Cewek', description: 'Dosen seksi rok span, memeknya kelihatan garis celana dalam saat duduk. Tatap matanya genit, napas berat – dia lagi memancing supaya kamu berani pegang memeknya di meja les sebelum kontolmu ngentot dia sampai squirt.', thumbnail: 'https://placeholder.com/200x300?text=Dosen+Cewek', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi power dynamic: Guru Privat. Perspektif Pria. Dia awalnya tegas tapi memberi cela (baju terbuka, posisi duduk). Slow-burn: memecah batas profesionalisme.' },
  { id: 'bos_perempuan_pria', title: 'Bos Perempuan Kantor', description: 'Bos galak tapi memeknya basah tiap lembur berdua. Tatap matanya ke kontolmu, paha gesek meja – sinyal dia lagi sange, siap dimancing sampai kamu angkat roknya dan masukin kontol ke memek bos di ruang meeting.', thumbnail: 'https://placeholder.com/200x300?text=Bos+Perempuan', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi lembur bos. Perspektif Pria. Bos dominan tapi ingin ditundukkan. Sinyal: perintah yang berubah jadi desahan, kaki menyilang menggoda. Slow-burn build-up.' },
  { id: 'istri_tetangga_pria', title: 'Istri Tetangga', description: 'Istri tetangga suaminya dinas, daster longgar bikin putingnya nongol. Napas cepat, tatap lama ke selangkanganmu – dia lagi memancing supaya kamu berani masuk rumahnya dan ngentot memeknya sampai squirt di kasur suaminya.', thumbnail: 'https://placeholder.com/200x300?text=Istri+Tetangga', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi Tetangga butuh bantuan. Perspektif Pria. Suami pergi. Sinyal: minta bantuan remeh tapi pakaian kurang pantas, sengaja memancing di area sepi. Slow-burn wajib.' },
  { id: 'baby_sitter_pria', title: 'Baby Sitter Cewek', description: 'Baby sitter muda pakai hotpants, memeknya basah saat anak tidur. Tatap genit, gigit bibir – sinyal dia lagi pengen kontolmu, siap dimancing sampai kamu angkat kakinya dan masukin kontol ke memeknya di sofa.', thumbnail: 'https://placeholder.com/200x300?text=Baby+Sitter', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi babysitter. Anak tidur. Sinyal: santai berlebihan, pakaian menggoda, nonton film dewasa samar-samar. Slow-burn memancing gadis muda.' },
  { id: 'ibu_teman_kuliah_pria', title: 'Ibu Teman Kuliah Anak Cewek', description: 'Ibu teman anak masih hot, rok ketat bikin kontolmu tegang. Napas berat, tatap ke selangkanganmu – dia lagi memancing supaya kamu berani pegang memeknya yang sudah licin sebelum ngentot dia di ruang tamu.', thumbnail: 'https://placeholder.com/200x300?text=Ibu+Teman+Kuliah', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi mature (MILF). Perspektif Pria. Obrolan nyambung yang mengarah ke pengalaman intim lama. Sinyal: keluhan soal suaminya yang kurang kuat, tatap mata intens. Slow-burn.' },
  { id: 'perawat_dokter_pria', title: 'Perawat / Dokter Klinik Cewek', description: 'Perawat seksi seragam ketat, memeknya basah saat check-up malam. Tatap genit, napas cepat – sinyal dia lagi sange, siap dimancing sampai kamu angkat roknya dan ngentot memeknya di ruang periksa.', thumbnail: 'https://placeholder.com/200x300?text=Perawat+Cewek', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi medis. Perspektif Pria. Pemeriksaan fisik yang jadi terlalu personal. Sinyal: detak jantung meningkat di kedua pihak, sentuhan medis yang terlalu meraba. Slow-burn.' },
  { id: 'mantan_pacar_istri_pria', title: 'Mantan Pacar Istri', description: 'Mantan pacar istri yang ketemu lagi, baju ketat bikin kontolmu keras. Tatap lama, gigit bibir – sinyal dia lagi pengen kontolmu lagi, siap dimancing sampai ngentot memeknya seperti dulu.', thumbnail: 'https://placeholder.com/200x300?text=Mantan+Istri', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi masa lalu/selingkuh. Sinyal: mengungkit momen paling intim dulu. Slow-burn wajib.' },
  { id: 'yoga_instructor_pria', title: 'Yoga Instructor Cewek', description: 'Yoga instructor tubuh kencang, legging ketat bikin kontolmu tegang. Napas berat, tatap ke selangkanganmu – sinyal dia lagi sange, siap dimancing sampai kamu pegang memeknya di matras.', thumbnail: 'https://placeholder.com/200x300?text=Yoga+Instructor', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi olahraga. Sinyal: rabaan untuk "bantu pose" yang terlalu sentuh area terlarang, napas berat. Slow-burn build-up fisik.' },
  { id: 'barista_kafe_pria', title: 'Barista Kafe Langganan Cewek', description: 'Barista cantik apron ketat, puting nongol samar. Tatap genit, napas cepat – sinyal dia lagi pengen kontolmu setelah tutup kafe, siap dimancing sampai ngentot memeknya di counter.', thumbnail: 'https://placeholder.com/200x300?text=Barista+Cewek', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi stranger/kafe. Setelah jam tutup malam hari. Sinyal: senyum sugestif, kasih bonus gratis (kue/kopi) sambil sentuh jari. Slow burn.' },

  // ==================== HETERO WANITA (10) ====================
  { id: 'adik_ipar_wanita', title: 'Adik Ipar Laki-Laki', description: 'Adik ipar laki-laki yang telanjang dada usai ngegym. Keringatnya bikin kamu basah. Tatap matanya melotot ke belahan dadamu – sinyal dia pengen ngentot kamu saat suami pergi. Pancing perlahan sampai dia menekan tubuh gaharnya ke kamu.', thumbnail: 'https://placeholder.com/200x300?text=Adik+Ipar+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi taboo: Adik Ipar Laki. Perspektif Wanita. Fokus deskripsi otot, keringat pria, suara berat maskulin. Sinyal: pria tatap tajam, napas memburu, tangan tremor kecil mau pegang. Slow-burn build-up memancing hasrat adik ipar.' },
  { id: 'kakak_ipar_wanita', title: 'Kakak Ipar Laki-Laki', description: 'Kakak ipar yang matang, tatapannya jauh lebih tajam dari suamimu. Dia "kebetulan" terus sentuh tanganmu di meja makan – sinyal jelas kontolnya keras membayangkan kamu.', thumbnail: 'https://placeholder.com/200x300?text=Kakak+Ipar+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi taboo: Kakak Ipar Pria. Kematangan pria dewasa. Slow-burn membaca sinyal gairah tersembunyi lewat pandangan curi-curi dan pembelaan di depan keluarga.' },
  { id: 'mertua_laki_wanita', title: 'Mertua Laki-Laki', description: 'Ayah mertua yang maskulin sehabis mandi, handuk melilit pinggangnya. Dia memanggilmu ke kamarnya, matanya terpaku ke pahamu – sinyal dominasi dia ingin pakai lubangmu malam ini.', thumbnail: 'https://placeholder.com/200x300?text=Mertua+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi taboo: Ayah Mertua. Pria dominan figur ayah (DILF). Menguji batas kesopanan perlahan.' },
  { id: 'bos_kantor_laki_wanita', title: 'Bos Kantor Laki-Laki', description: 'Bos wibawa yang buka jas saat lembur. Urat lengannya menonjol, suaranya makin serak pas manggil namamu – pancing terus sampai dia robohin kamu di meja kerjanya.', thumbnail: 'https://placeholder.com/200x300?text=Bos+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi bos dominan. Sinyal: buka kancing kemeja, melonggarkan dasi, suara makin serak, tatapan memerintah.' },
  { id: 'dosen_guru_laki_wanita', title: 'Dosen / Guru Privat Laki-Laki', description: 'Dosen pintar berkacamata malam-malam di rumah. Tangannya "nggak sengaja" sentuh paha menekan kamu saat jelaskan materi – otaknya lagi mikir cara masuki memek kamu.', thumbnail: 'https://placeholder.com/200x300?text=Dosen+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi edukasi, pria cerdas. Sinyal: mengoreksi posisi tapi terlalu intim, napas tersengal menahan diri.' },
  { id: 'pembantu_laki_wanita', title: 'Pembantu / Supir Ganteng', description: 'Supir muda dengan keringat di dada. Habis angkat galon, kaos basahnya nyeplak. Matanya melirik nakal ke daster tipismu – tinggal minta dipijit, dia pasti akan pijat sampai area terdalammu.', thumbnail: 'https://placeholder.com/200x300?text=Pembantu+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi wanita dominan ke pria pekerja (supir/art/tukang kebun). Sinyal: kepatuhan yang bercampur gairah, keringat.' },
  { id: 'tetangga_laki_wanita', title: 'Tetangga Sebelah Laki-Laki', description: 'Tetangga duren pasang pipa di apartemenmu. Suaranya ngebass, wangi parfum musk-nya nyampur bau cowok. Kontolnya ngecap di celananya waktu dia nunduk.', thumbnail: 'https://placeholder.com/200x300?text=Tetangga+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi benerin barang/tetangga. Pria tangguh. Sinyal pamer otot tanpa sadar, ruang sempit.' },
  { id: 'suami_sahabat_wanita', title: 'Suami Sahabat Terbaik', description: 'Suami sahabatmu yang ganteng nawarin anter pulang pas mabuk. Di mobil, tangannya pindah gigi sering banget nyenggol pahamu – pura-pura tidur aja biar dia berani meraba.', thumbnail: 'https://placeholder.com/200x300?text=Suami+Sahabat', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi terlarang/perselingkuhan. Adrenalin nyetir/tempat tertutup. Sinyal: melindungi tapi memegang batas paha, napas panas dekat leher.' },
  { id: 'sepupu_laki_wanita', title: 'Sepupu Kandung Laki-Laki', description: 'Sepupu cowokmu habis mandi. Nostalgia masa kecil berujung sikat badan di ruang ganti. Matanya berkabut nafsu setiap kamu nyender manja.', thumbnail: 'https://placeholder.com/200x300?text=Sepupu+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi reunian sepupu dekat. Sinyal keakraban fisik yang kebablasan jadi gairah murni.' },
  { id: 'dokter_perawat_laki_wanita', title: 'Dokter / Perawat Laki-Laki', description: 'Dokter spesialis yang jari-jarinya sangat ahli. Pemeriksaannya turun terlalu rendah, napasnya memburu di balik maskernya. Dokter itu mau resepkan orgasme malam ini.', thumbnail: 'https://placeholder.com/200x300?text=Dokter+Laki', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi Medis. Sentuhan profesional yang berubah abusif sensual perlahan. Pria pintar.' },

  // ==================== LESBIAN (10) ====================
  { id: 'adik_ipar_perempuan', title: 'Adik Ipar Perempuan', description: 'Adik ipar perempuan yang flirty saat saudara laki-laki tidur, sinyal tatap mata dan nyender. Dada nya kebukaan nunjukin belahan. Bibirnya menjilat bibir, pertanda dia mau ngerasain lidah perempuan.', thumbnail: 'https://placeholder.com/200x300?text=Adik+Ipar+Perempuan', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi taboo: Adik Ipar. Perspektif Wanita Lesbian. Fokus slow-burn tarik menarik batas keluarga.' },
  { id: 'kakak_ipar_perempuan', title: 'Kakak Ipar Perempuan', description: 'Kakak ipar dewasa yang mengajari "rahasia wanita" di acara keluarga. Jari-jari lentiknya meraba bahumu sampai bulu kuduk ngeri. Wanginya manis, paha mulusnya terbuka mengundang sentuhan.', thumbnail: 'https://placeholder.com/200x300?text=Kakak+Ipar+Perempuan', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi taboo: Kakak Ipar Mature. Sinyal bimbingan erotis sesama perempuan. Slow-burn dominasi kakak ipar.' },
  { id: 'istri_sahabat_perempuan', title: 'Istri Sahabat Terbaik', description: 'Istri sahabat yang mabuk curhat tentang suaminya yang payah. Menangis peluk kamu, dadanya nempel keras ke dadamu. Napasnya terengah, bilang "coba suamiku selembut kamu".', thumbnail: 'https://placeholder.com/200x300?text=Istri+Sahabat', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi selingkuh dari sahabat pria. Momen curhat jadi panas. Sentuhan comforting yang turun ke paha dan klitoris.' },
  { id: 'tetangga_cewek_perempuan', title: 'Tetangga Cewek Sebelah', description: 'Cewek tetangga pinjam gula pakai lingerie tipis. Gigit bibir, matanya nyisir dari dada sampai pantatmu. Dia ngundang masuk dengan alasan cicipin wine, memek sama memek mau diadu malem ini.', thumbnail: 'https://placeholder.com/200x300?text=Tetangga+Cewek', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi tetangga apartemen. Eksplorasi genit di ruang privat. Sinyal eye-contact dan pujian tubuh eksplisit.' },
  { id: 'teman_kantor_cewek_perempuan', title: 'Teman Kantor Cewek', description: 'Lembur berdua sesama cewek. Sepatunya dicopot, kaki telanjangnya gesek betis kamu di bawah meja. Wangi femininnya memenuhi ruangan, jarinya minta diemut dari tadi.', thumbnail: 'https://placeholder.com/200x300?text=Teman+Kantor+Cewek', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi lembur kantor. Sinyal main rambut, buka 1 kancing kemeja kantor, dan gesekan kaki di kolong meja.' },
  { id: 'dosen_guru_perempuan', title: 'Dosen / Guru Privat Perempuan', description: 'Dosen cantik yang pegang tanganmu saat mengoreksi tugas. Sentuhannya dingin tapi ngasih aliran listrik. Kacamata melorot, matanya penuh gairah – gairah perempuan matang meraba mahasiswinya.', thumbnail: 'https://placeholder.com/200x300?text=Dosen+Perempuan', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi Dosen-Mahasiswi. Power dynamic. Sinyal tatapan merendahkan tapi erotis, otoritas di ranjang.' },
  { id: 'tante_perempuan', title: 'Tante Perempuan Milf', description: 'Tante seksi (istri om) di liburan vila sedunia. Baju renangnya transparan di kolam. Dia raba pinggangmu dari bawah air, berbisik kotor ngundang kamu ke kamarnya buat ngerasain kenikmatan sejati.', thumbnail: 'https://placeholder.com/200x300?text=Tante+Perempuan', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi MILF lesbian. Di kolam renang/vila. Eksplorasi tubuh bawah air.' },
  { id: 'pembantu_art_perempuan', title: 'Pembantu ART Cewek', description: 'ART muda lagi ngepel basah-basahan keringat. Payudaranya mantul. Tatapannya menantang nyonya rumah buat ngajarin cara bersihin hal lain di kursi tamu.', thumbnail: 'https://placeholder.com/200x300?text=Pembantu+Cewek', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi Nyonya-Pelayan. Dominasi nyonya perempuan.' },
  { id: 'sahabat_kuliah_perempuan', title: 'Sahabat Lama / Mantan SMA', description: 'Sahabat cewek jaman SMA ketemu lagi makin semok. Nginep bareng satu kasur kos. Pahanya meluk pahamu pas tidur, pura-pura ngigau sambil jari telunjuknya raba basah celana dalammu.', thumbnail: 'https://placeholder.com/200x300?text=Sahabat+Kuliah', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi nostalgia menginap. Tidur satu ranjang, pura-pura tidur.' },
  { id: 'ibu_teman_perempuan', title: 'Ibu Teman Anak / Mertua Perempuan', description: 'Ibu teman seksi pas nyobain wine berdua. Bibir memerah kena wine, tangannya licin ngeraba lenganmu ke arah payudara – ngajari cewek muda kalau umur hanyalah angka untuk orgasme muncrat memek.', thumbnail: 'https://placeholder.com/200x300?text=Ibu+Teman+Perempuan', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi age-gap lesbian. Sinyal alkohol, pujian berlebih, kedekatan sentuhan paha.' }
];

async function seed() {
  console.log('🌱 Memulai seeder database... menghapus data lama...');
  
  // Hapus semua data
  const { error: dropSessionsErr } = await supabase.from('story_sessions').delete().neq('scenario_id', 'dummy_string');
  if (dropSessionsErr) console.log('Error hapus sessions:', dropSessionsErr);

  const { error: delErr } = await supabase.from('scenarios').delete().neq('id', 'dummy');
  if (delErr) {
    console.error('Gagal hapus data:', delErr);
    return;
  }

  console.log('✨ Memasukkan 35 Skenario VULGAR SLOW-BURN PDF...');
  
  const { data, error } = await supabase
    .from('scenarios')
    .insert(scenarios)
    .select();

  if (error) {
    console.error('Gagal insert data:', error);
  } else {
    console.log(`✅ Berhasil memasukkan ${data.length} skenario.`);
  }
}

seed();
