// Seed script: jalankan dengan `node seed.mjs`
// Membersihkan data lama dan insert 35 skenario baru ke Supabase

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Baca .env.local
const envContent = readFileSync(join(__dirname, '.env.local'), 'utf8');
const env = Object.fromEntries(
  envContent.split('\n')
    .filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => l.split('=').map(s => s.trim()))
);

const supabaseUrl = env['NEXT_PUBLIC_SUPABASE_URL'];
const supabaseKey = env['SUPABASE_SERVICE_ROLE_KEY'] || env['NEXT_PUBLIC_SUPABASE_ANON_KEY'];

if (!supabaseUrl || !supabaseKey || supabaseUrl.includes('YOUR_')) {
  console.error('❌ Supabase URL/KEY tidak ditemukan di .env.local');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const scenarios = [
  // ==================== HETERO PRIA (15) ====================
  { id: 'adik_ipar_pria', title: 'Adik Ipar', description: 'Adik ipar yang selalu hadir di momen paling tidak terduga — dan paling menggoda.', thumbnail: 'https://picsum.photos/id/1015/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi taboo: Adik Ipar Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan karakter adik ipar secara detail: nama Indonesia cantik, usia 22-27 tahun, fisik menggoda, kepribadian, latar belakang. Jelaskan bagaimana hubungan keluarga ini terbentuk dan kenapa mereka ada berdua. Slow-burn build-up minimal 5 scene. Gaya prosa sastra Indonesia kaya detail.' },
  { id: 'kakak_ipar_pria', title: 'Kakak Ipar Cewek', description: 'Kakak ipar yang tegas di depan suaminya, lain cerita saat kalian berdua.', thumbnail: 'https://picsum.photos/id/1027/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi taboo: Kakak Ipar Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan kakak ipar: nama Indonesia, usia 28-35, fisik montok dan matang. Konteks: rumah kakak ipar, suami sedang dinas luar kota. Slow-burn 5 scene, gaya sastra Indonesia.' },
  { id: 'ibu_mertua_pria', title: 'Ibu Mertua', description: 'Wanita yang melahirkan istrimu — dan ternyata ia juga wanita yang membuatmu tak bisa tidur.', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi taboo: Ibu Mertua. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan ibu mertua: nama Indonesia elegan, usia 45-52 tahun, masih sangat menarik. Latar belakang: PRIA menginap di rumah mertua selagi istri mudik. Slow-burn 5 scene.' },
  { id: 'pembantu_art_pria', title: 'Pembantu Rumah (ART)', description: 'Ia datang setiap pagi untuk bersihkan rumah — dan perlahan mulai mengacaukan pikiranmu.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Pembantu ART Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan ART: nama Jawa/Sunda, usia 20-25 tahun, polos tapi menawan. Konteks: rumah sepi, istri/pasangan ke luar kota seminggu. Slow-burn 5 scene.' },
  { id: 'istri_sahabat_pria', title: 'Istri Sahabat Terbaik', description: 'Sahabatmu menikah dengan wanita luar biasa — dan tanpa sengaja kamu mulai jatuh pada matanya.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Istri Sahabat Terbaik. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan istri sahabat: nama Indonesia modern, usia 27-32. Konteks: acara ulang tahun sahabat. Slow-burn 5 scene.' },
  { id: 'sepupu_pria', title: 'Sepupu Jauh yang Kembali', description: 'Bertahun-tahun tak bertemu — dan saat ia kembali, semuanya berbeda.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Sepupu Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan sepupu: nama Indonesia, usia 23-28, baru pulang dari luar kota/negeri. Konteks: reuni keluarga atau menginap bersama. Slow-burn 5 scene.' },
  { id: 'dosen_privat_pria', title: 'Dosen / Guru Privat', description: 'Ia mengajarimu ilmu — tapi tatapan matanya mengajarkan hal yang berbeda.', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Dosen/Guru Privat Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan dosen: nama Indonesia profesional, usia 30-38. Konteks: les privat di apartemen dosen, malam hari. Slow-burn 5 scene.' },
  { id: 'bos_perempuan_pria', title: 'Bos Perempuan Kantor', description: 'Ia yang menentukan kariermu — dan malam lembur ini ia juga menentukan sesuatu yang lain.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Bos Perempuan. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan bos: nama Indonesia karir, usia 35-42. Konteks: lembur berdua di kantor, deadline besok. Slow-burn 5 scene.' },
  { id: 'istri_tetangga_pria', title: 'Istri Tetangga', description: 'Suaminya pergi dinas — ia ketuk pintumu minta bantuan pasang lampu.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Istri Tetangga. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan istri tetangga: nama Indonesia, usia 28-35. Konteks: malam hari, suami dinas, ia meminta bantuan. Slow-burn 5 scene.' },
  { id: 'baby_sitter_pria', title: 'Baby Sitter Cewek', description: 'Kamu mempercayakan si kecil padanya — dan malam ini ia menaruh kepercayaan yang lain padamu.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Baby Sitter Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan baby sitter: nama Indonesia muda, usia 19-24, mahasiswi. Konteks: anak sudah tidur, PRIA pulang terlambat. Slow-burn 5 scene.' },
  { id: 'perawat_dokter_pria', title: 'Perawat / Dokter Klinik', description: 'Check-up malam yang mengungkap lebih dari sekadar kondisi kesehatan.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Perawat/Dokter Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan dokter/perawat: nama Indonesia profesional, usia 26-33. Konteks: klinik sepi malam hari. Slow-burn 5 scene.' },
  { id: 'mantan_pacar_pria', title: 'Mantan Pacar yang Kembali', description: 'Lima tahun berpisah — dan satu pertemuan tak terduga menghidupkan kembali segala yang pernah ada.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Mantan Pacar. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan mantan: nama Indonesia, usia 25-30, banyak berubah tapi lebih menarik. Konteks: bertemu tidak sengaja di kafe. Slow-burn 5 scene.' },
  { id: 'yoga_instructor_pria', title: 'Yoga Instructor Cewek', description: 'Setiap gerakan yang ia pandu mengisyaratkan kelenturan yang lebih dari sekadar tubuh.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Yoga Instructor. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan instruktur: nama Indonesia modern, usia 24-30. Konteks: sesi yoga privat di studio kecil. Slow-burn 5 scene.' },
  { id: 'barista_kafe_pria', title: 'Barista Kafe Langganan', description: 'Ia selalu ingat pesananmu — dan hari ini ia menambahkan sesuatu yang berbeda di balik senyumannya.', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Barista Cewek. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan barista: nama Indonesia trendi, usia 20-26. Konteks: kafe mau tutup, pelanggan tersisa hanya PRIA. Slow-burn 5 scene.' },
  { id: 'teman_lama_pria', title: 'Teman Lama yang Jadi Tetangga', description: 'Teman SMA yang pindah ke apartemen sebelahmu — kedekatan masa lalu dan jarak yang kini hanya selapis dinding.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'hetero_pria', gender_target: 'male', base_prompt: 'Fantasi: Teman Lama. Pembaca adalah PRIA (sudut pandang orang pertama pria). Perkenalkan teman lama: nama Indonesia, usia 27-32, nostalgia masa SMA/kuliah. Konteks: baru pindah ke apartemen sebelah. Slow-burn 5 scene.' },

  // ==================== HETERO WANITA (10) ====================
  { id: 'adik_ipar_wanita', title: 'Adik Ipar Laki-Laki', description: 'Adik suami yang diam-diam membuatmu sadar bahwa ada rasa yang tidak seharusnya ada.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi taboo: Adik Ipar Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan adik ipar: nama Indonesia maskulin, usia 22-27, kekar dan tampan. Slow-burn 5 scene.' },
  { id: 'kakak_ipar_wanita', title: 'Kakak Ipar Laki-Laki', description: 'Pria tertampan yang pernah kamu kenal — sayangnya ia sudah menikahi adikmu.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi taboo: Kakak Ipar Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan kakak ipar: nama Indonesia dewasa, usia 30-38. Konteks: adik (istrinya) sedang keluar. Slow-burn 5 scene.' },
  { id: 'mertua_laki_wanita', title: 'Mertua Laki-Laki', description: 'Ayah suamimu — diam, berwibawa, dan akhir-akhir ini terlalu memperhatikanmu.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi taboo: Mertua Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan mertua: nama Indonesia matang, usia 48-55, masih gagah. Konteks: WANITA menginap di rumah mertua, suami sedang dinas. Slow-burn 5 scene.' },
  { id: 'bos_kantor_laki_wanita', title: 'Bos Kantor Laki-Laki', description: 'Lembur berdua dengannya selalu begitu produktif — dan malam ini produktivitasnya berbeda arah.', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi: Bos Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan bos: nama Indonesia karir, usia 36-44. Konteks: lembur malam di kantor. Slow-burn 5 scene.' },
  { id: 'dosen_guru_laki_wanita', title: 'Dosen / Guru Privat Laki-Laki', description: 'Ia mengajarimu dengan sabar — dan kesabarannya membuat sesuatu dalam dirimu tak sabar.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi: Dosen Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan dosen: nama Indonesia, usia 32-40. Konteks: les privat, perpustakaan sepi. Slow-burn 5 scene.' },
  { id: 'tetangga_laki_wanita', title: 'Tetangga Sebelah', description: 'Ia yang selalu menawarkan bantuan — dan malam ini kamu baru tahu maksud sebenarnya.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi: Tetangga Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan tetangga: nama Indonesia, usia 28-35. Konteks: apartemen, WANITA tinggal sendiri. Slow-burn 5 scene.' },
  { id: 'suami_sahabat_wanita', title: 'Suami Sahabat Terbaik', description: 'Sahabatmu menikah dengan pria sempurna — dan sempurna itu bukan untuk matamu saja.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi: Suami Sahabat Terbaik. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan suami sahabat: nama Indonesia, usia 30-36. Konteks: acara sosial, sahabat ke toilet. Slow-burn 5 scene.' },
  { id: 'dokter_perawat_laki_wanita', title: 'Dokter / Perawat Laki-Laki', description: 'Tangan dinginnya menyentuh kulit, denyut nadimu tiba-tiba berakselerasi bukan karena demam.', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi: Dokter Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan dokter: nama Indonesia, usia 30-38. Konteks: klinik malam. Slow-burn 5 scene.' },
  { id: 'personal_trainer_wanita', title: 'Personal Trainer', description: 'Setiap sesi ia koreksi posturmu — dan kamu mulai meragukan apakah itu murni profesional.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi: Personal Trainer Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan trainer: nama Indonesia sporty, usia 26-33. Konteks: gym privat, sesi pagi. Slow-burn 5 scene.' },
  { id: 'pilot_layover_wanita', title: 'Pilot di Layover', description: 'Penerbangan tertunda, satu malam di hotel yang sama, dan ia duduk tepat di sebelahmu di bar.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'hetero_wanita', gender_target: 'female', base_prompt: 'Fantasi: Pilot/Penumpang Laki-Laki. Pembaca adalah WANITA (sudut pandang orang pertama wanita). Perkenalkan pria: nama Indonesia, usia 32-40, seragam pilot. Konteks: hotel transit, bar lounge. Slow-burn 5 scene.' },

  // ==================== LESBIAN (10) ====================
  { id: 'adik_ipar_lesbian', title: 'Adik Ipar Perempuan', description: 'Adik ipar yang selalu membuatmu bertanya — mengapa ia bukan orang lain saja.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi taboo: Adik Ipar Perempuan. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan adik ipar: nama Indonesia, usia 20-25, manis dan bersahaja. Slow-burn 5 scene.' },
  { id: 'kakak_ipar_lesbian', title: 'Kakak Ipar Perempuan', description: 'Pernikahan suamimu mempertemukanmu dengan kakaknya — dan pertemuan itu terasa seperti takdir yang salah arah.', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi taboo: Kakak Ipar Perempuan. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan kakak ipar: nama Indonesia, usia 30-37, matang dan mandiri. Slow-burn 5 scene.' },
  { id: 'sahabat_lama_lesbian', title: 'Sahabat Lama yang Beda', description: 'Semua yang pernah ada di antara kalian — kadang persahabatan adalah kata yang terlalu sempit.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Sahabat Lama. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan sahabat: nama Indonesia, usia 24-30, teman sejak SMA/kuliah. Konteks: reunian, menginap bersama. Slow-burn 5 scene.' },
  { id: 'teman_kantor_lesbian', title: 'Teman Kantor Cewek', description: 'Lembur selalu bersamanya — dan lama-lama kamu sadar bahwa itu bukan kebetulan.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Teman Kantor Cewek. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan teman kantor: nama Indonesia, usia 25-30. Konteks: lembur malam, kantor sepi. Slow-burn 5 scene.' },
  { id: 'dosen_lesbian', title: 'Dosen / Instruktur Perempuan', description: 'Caranya memandangmu saat menjelaskan terasa seperti ia mengajarimu lebih dari sekadar teori.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Dosen/Instruktur Perempuan. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan dosen: nama Indonesia, usia 30-38. Konteks: bimbingan privat. Slow-burn 5 scene.' },
  { id: 'tetangga_cewek_lesbian', title: 'Tetangga Cewek Sebelah', description: 'Setiap malam ada cahaya dari jendela sebelah — dan suatu malam ia ketuk pintumu.', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Tetangga Cewek. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan tetangga: nama Indonesia, usia 23-28. Konteks: apartemen, suatu malam berinteraksi lebih. Slow-burn 5 scene.' },
  { id: 'roommate_lesbian', title: 'Teman Kost / Roommate', description: 'Tinggal serumah ternyata memiliki konsekuensi yang tidak pernah kamu bayangkan.', thumbnail: 'https://picsum.photos/id/251/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Teman Kost/Roommate. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan roommate: nama Indonesia, usia 20-25. Konteks: tinggal bersama, sering berinteraksi. Slow-burn 5 scene.' },
  { id: 'tante_lesbian', title: 'Tante yang Masih Muda', description: 'Ia sering dipanggil tante — padahal usianya tak jauh beda, dan sikapnya jauh dari keibuan.', thumbnail: 'https://picsum.photos/id/133/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Tante Muda. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan tante: nama Indonesia, usia 30-36, cool dan mandiri. Slow-burn 5 scene.' },
  { id: 'barista_lesbian', title: 'Barista Kafe Favorit', description: 'Ia selalu menggambar bunga kecil di cup-mu — dan hari ini ia menambahkan nomornya.', thumbnail: 'https://picsum.photos/id/180/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Barista Lesbian. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan barista: nama Indonesia, usia 20-24, androgyn stylish. Slow-burn 5 scene.' },
  { id: 'dokter_suster_lesbian', title: 'Dokter / Perawat Wanita', description: 'Pemeriksaan yang seharusnya dingin dan profesional — mengapa tangannya terasa begitu hangat?', thumbnail: 'https://picsum.photos/id/201/300/400', category: 'lesbian', gender_target: 'female_lesbian', base_prompt: 'Fantasi: Dokter/Perawat Wanita. Pembaca adalah WANITA lesbian (sudut pandang orang pertama wanita). Perkenalkan dokter: nama Indonesia, usia 28-35. Konteks: klinik malam. Slow-burn 5 scene.' },
];

async function seed() {
  console.log('🗑️  Menghapus data lama...');
  await supabase.from('story_sessions').delete().neq('id', '00000000-0000-0000-0000-000000000000');
  const { error: delErr } = await supabase.from('scenarios').delete().neq('id', '___');
  if (delErr) console.warn('  ⚠️ Delete warning:', delErr.message);

  console.log('📥 Memasukkan 35 skenario...');
  const { error, count } = await supabase
    .from('scenarios')
    .insert(scenarios, { count: 'exact' });

  if (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }

  console.log(`✅ Berhasil! ${count ?? scenarios.length} skenario berhasil dimasukkan.`);
  console.log('   15 Hetero Pria | 10 Hetero Wanita | 10 Lesbian');
}

seed();
